name       : krunner
version    : 5.48.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/krunner-5.48.0.tar.xz : 169a79a0067dc2702a12f9c67433762e2223b2441c93b7f9456a9962faf6bc55
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
