name       : krunner
version    : 5.45.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/krunner-5.45.0.tar.xz : 3d49a1a8e8e9bf98c86d30c7e5970e45b915eb58e5623874291de5debe2d38a3
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
