name       : krunner
version    : 5.82.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/krunner-5.82.0.tar.xz : e8ca703e7e2ac97c4b4d4377802f8d407dff6d636caafdbf2d5b9c212c1fb37d
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - ki18n-devel
    - kio-devel
    - kpackage-devel
    - plasma-framework-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
