name       : krunner
version    : 5.79.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/krunner-5.79.0.tar.xz : 91a99cf7a5bd4eed6f272fa0d90a02312a9194660ccef80e67066465a252ee6c
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - ki18n-devel
    - kio-devel
    - kpackage-devel
    - plasma-framework-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
