name       : krunner
version    : 5.36.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.36/krunner-5.36.0.tar.xz : 1856e17a2fd8d6ad94f463fe2cb44d7377439650dd47f88444e924d650e32165
license    : LGPL-2.1
component  : programming
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - plasma-framework-devel
    - solid-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
