name       : krunner
version    : 5.90.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/krunner-5.90.0.tar.xz : f16546d24f307e7ca79948af8ad4c1a2a9483bb717db8c7c439b1c5168d570e0
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - ki18n-devel
    - kio-devel
    - kpackage-devel
    - plasma-framework-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
