name       : krunner
version    : 5.66.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/krunner-5.66.0.tar.xz : b7d67d61c0b0f96128c143e3d2694dc5ced88a7de73db0f4493f084de9dc9701
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - plasma-framework-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
