name       : krunner
version    : 5.41.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/krunner-5.41.0.tar.xz : 037537791cea4b90056e7ac113d424fab080d120a16d757e0aeada0db48cdd6f
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - solid-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
