name       : krunner
version    : 5.63.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/krunner-5.63.0.tar.xz : aa58b6301de114e7f0a420982f1387dfadac2112aac1339182af18f4f4e7583e
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - plasma-framework-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
