name       : krunner
version    : 5.54.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/krunner-5.54.0.tar.xz : 1be00fe8847c9e6389ceb95cb077018a8d1380f4f97a1513e6462431b648c51b
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Framework for Plasma runners
description: |
    The Plasma workspace provides an application called KRunner which, among other things, allows one to type into a text area which causes various actions and information that match the text appear as the text is being typed.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - threadweaver-devel
rundeps    :
    - devel :
        - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
